'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ShelterClientDetails
    
    '''<summary>
    '''pnlError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFirstName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSurname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSurname As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNationalIDNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNationalIDNum As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''radDtDOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radDtDOB As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''cboSex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboSex As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtClientContactNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClientContactNumber As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cboDistricts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDistricts As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cboWards control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboWards As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtArrivalTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtArrivalTime As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTotalPeopleAdmitted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalPeopleAdmitted As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtClientPermanentAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClientPermanentAddress As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cboMaritalStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboMaritalStatus As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cboEmpoymentStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboEmpoymentStatus As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtEmployerTelNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmployerTelNumber As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEmployerAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmployerAddress As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtReferredBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReferredBy As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtReferrerTelNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReferrerTelNum As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cboEverSheltered control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboEverSheltered As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cboSkillsToNature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboSkillsToNature As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtSkillsToNature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSkillsToNature As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEmergencyContactName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmergencyContactName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtRelationToEmergencyContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRelationToEmergencyContact As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEmergencyContactNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmergencyContactNumber As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEmergencyContactAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmergencyContactAddress As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtInjuries control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInjuries As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cboSpecialNeeds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboSpecialNeeds As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtSpecialNeeds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSpecialNeeds As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCarePlan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCarePlan As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPresentingProblem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPresentingProblem As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cmdSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSave As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtShelterClientDetailID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShelterClientDetailID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtBeneficiaryID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBeneficiaryID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAddressID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddressID As Global.System.Web.UI.WebControls.TextBox
End Class
