'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4952
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class CustomFieldsBulkAssign
    Protected WithEvents cboFieldName As System.Web.UI.WebControls.DropDownList
    Protected WithEvents chkFilterByValue As System.Web.UI.WebControls.CheckBox
    Protected WithEvents cboFieldValues As System.Web.UI.WebControls.DropDownList
    Protected WithEvents txtNewValue As System.Web.UI.WebControls.TextBox
    Protected WithEvents cmdUpdate As System.Web.UI.WebControls.Button
    Protected WithEvents cboTemplates As System.Web.UI.WebControls.DropDownList
    Protected WithEvents cmdAssignCustomFieldTemplate As System.Web.UI.WebControls.Button
    Protected WithEvents cmdRemoveCustomFieldTemplate As System.Web.UI.WebControls.Button
End Class
