'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CustomFieldTemplates

    '''<summary>
    '''ValidationSummary1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''pnlError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboTemplates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboTemplates As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cmdManageTemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdManageTemplate As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''cmdRenameTemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRenameTemplate As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlRenameTemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRenameTemplate As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblTemplateName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTemplateName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRenameTemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRenameTemplate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmdUpdateTemplateRename control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdUpdateTemplateRename As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''cmdCancelTemplateRename control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdCancelTemplateRename As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''chkApplyToAllNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkApplyToAllNew As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''radgTemplates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radgTemplates As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''txtTemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTemplate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboTemplateType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboTemplateType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cmdAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAdd As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdUpdateMissingTemplateFields control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdUpdateMissingTemplateFields As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cboApplyTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboApplyTo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cmdClearAutoApplyRules control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdClearAutoApplyRules As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblRules control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRules As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmdRemoveAllUsed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRemoveAllUsed As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ucAppliesTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucAppliesTo As Global.WebSysME.ComplementaryListboxes

    '''<summary>
    '''cmdSaveAppliesTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSaveAppliesTo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdApplyTemplateToExisting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdApplyTemplateToExisting As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdDeleteOrphanTemplates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDeleteOrphanTemplates As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdRefreshCFView_Projects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRefreshCFView_Projects As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdRefreshCFView_Contacts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRefreshCFView_Contacts As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdRefreshCFView_Documents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRefreshCFView_Documents As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtNewFields control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewFields As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTemplateFields control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTemplateFields As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTemplateNames control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTemplateNames As Global.System.Web.UI.WebControls.TextBox
End Class
