'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CustomFields

    '''<summary>
    '''ControlsTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ControlsTable As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''radtabFilterTabs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radtabFilterTabs As Global.Telerik.Web.UI.RadTabStrip

    '''<summary>
    '''radmpFilterTabs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radmpFilterTabs As Global.Telerik.Web.UI.RadMultiPage

    '''<summary>
    '''txtDBFields control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDBFields As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ucRadWindowManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ucRadWindowManager As Global.Telerik.Web.UI.RadWindowManager
End Class
